### ISSUE TITLE
NullPointerException when interrupting scanning by turning off bluetooth

### ISSUE THREAD

**Issue by CTMBNara** [JuulLabs/kable#164]
Steps to reproduce:
- Start scanning
- Turn off bluetooth via android UI
- NullPointerException will be thrown

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: some.project.android, PID: 7248
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.le.BluetoothLeScanner.stopScan(android.bluetooth.le.ScanCallback)' on a null object reference
        at com.juul.kable.AndroidScanner$advertisements$1$2.invoke(Scanner.kt:71)
        at com.juul.kable.AndroidScanner$advertisements$1$2.invoke(Scanner.kt:70)
        at kotlinx.coroutines.channels.ProduceKt.awaitClose(Produce.kt:58)
        at kotlinx.coroutines.channels.ProduceKt$awaitClose$1.invokeSuspend(Unknown Source:13)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by sdonn3** [comment]
As we are no longer attempting to retrieve the scanner in scenarios when BLE is disabled, https://github.com/JuulLabs/kable/pull/187 should solve this issue
