### ISSUE TITLE
Incorrect (`CancellationException`) thrown during I/O operation

### ISSUE THREAD

**Issue by twyatt** [JuulLabs/kable#194]
It seems very rare, but it is possible that `CancellationException` is thrown from an I/O operation if the connection is lost at a specific time during the operation (during the request phase):

https://github.com/JuulLabs/kable/blob/ed0e4f59b5c2bd3bd8b4a5fa37e49cc5f002cd2f/core/src/androidMain/kotlin/Connection.kt#L55-L57

If `dispatcher` is shutdown (due to connection loss) before the above is called, then a `CancellationException` may be thrown.

Snippet of the exception thrown is as follows:

```
2021-11-22 15:47:17.486 29287-29936/com.<redacted> D/Kable/Peripheral: <redacted> write
    service: <redacted>
    characteristic: <redacted>
    writeType: WithoutResponse
    data: <redacted>
2021-11-22 15:47:17.492 29287-29936/com.<redacted> W/MessageQueue: Handler (android.os.Handler) {78f626c} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {78f626c} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
        at android.os.Handler.enqueueMessage(Handler.java:778)
        at android.os.Handler.sendMessageAtTime(Handler.java:727)
        at android.os.Handler.sendMessageDelayed(Handler.java:697)
        at android.os.Handler.post(Handler.java:427)
        at kotlinx.coroutines.android.HandlerContext.dispatch(HandlerDispatcher.kt:139)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:322)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:170)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at com.juul.kable.AndroidPeripheral.write(Peripheral.kt:651)
        <redacted<
        at kotlinx.coroutines.flow.SubscribedFlowCollector.onSubscription(Share.kt:410)
        at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:341)
        at kotlinx.coroutines.flow.ReadonlySharedFlow.collect(Unknown Source:2)
        at kotlinx.coroutines.flow.SubscribedSharedFlow.collect(Share.kt:400)
        <redacted>
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:212)
        at kotlinx.coroutines.flow.FlowKt__ReduceKt.first(Reduce.kt:222)
        at kotlinx.coroutines.flow.FlowKt.first(Unknown Source:1)
        <redacted>
2021-11-22 15:47:17.492 29287-29936/com.<redacted> W/MessageQueue:     at com.<redacted>$4.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
        at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
        at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:104)
        <redacted>
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>: Stopped <redacted>
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>: java.util.concurrent.CancellationException: The task was rejected, the handler underlying the dispatcher 'Handler (android.os.Handler) {78f626c}' was closed
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.android.HandlerContext.cancelOnRejection(HandlerDispatcher.kt:164)
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.android.HandlerContext.dispatch(HandlerDispatcher.kt:140)
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:322)
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:170)
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at com.juul.kable.AndroidPeripheral.write(Peripheral.kt:651)
<redacted>
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.flow.SubscribedFlowCollector.onSubscription(Share.kt:410)
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:341)
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.flow.ReadonlySharedFlow.collect(Unknown Source:2)
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.flow.SubscribedSharedFlow.collect(Share.kt:400)
<redacted>
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:212)
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.flow.FlowKt__ReduceKt.first(Reduce.kt:222)
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.flow.FlowKt.first(Unknown Source:1)
<redacted>
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:104)
<redacted>
2021-11-22 15:47:17.499 29287-29936/com.<redacted> I/<redacted>:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2021-11-22 15:47:17.500 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2021-11-22 15:47:17.500 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2021-11-22 15:47:17.500 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2021-11-22 15:47:17.500 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2021-11-22 15:47:17.500 29287-29936/com.<redacted> I/<redacted>:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by twyatt** [comment]
With #197, `CancellationException` may still be thrown, but only in instances where the `Peripheral` has been disposed (i.e. parent Coroutine has been cancelled).

So, this is resolved, as `CancellationException` should no longer be thrown as the result of a connection drop (only `Peripheral` disposal).

**Comment by twyatt** [comment]
To add additional details on what was causing the issue: the underlying thread/handler were being shutdown and subsequent I/O that tried to use the thread/dispatcher would be hit with a `CancellationException` (from the shut down thread/handler) and it was allowed to propagate.

The resolution (in #197) was to keep the underlying thread/handler alive (until `Peripheral` is disposed). This means that we no longer hit the `CancellationException`s because the threads/handlers are not shutdown between connections (so we are not longer susceptible to the potential race conditions.

The `CancellationException`s may still be thrown because if a `Peripheral` is disposed then subsequent I/O could still hit the previous behavior. But in that situation, cancelling callers would make sense, as the `Peripheral` is no longer usable.
