### ISSUE TITLE
IllegalStateException when using GlobalScope with CoroutineScope.peripheral in 0.28.0

### ISSUE THREAD

**Issue by JonatanPlesko** [JuulLabs/kable#622]
Trying to get the peripheral using GlobalScope as a receiver for the CoroutineScope.peripheral extension function in the latest version (0.28.0) throws the following exception:
``` 
java.lang.IllegalStateException: Current context doesn't contain Job in it: com.myproject.di.modules.DomainModule$createConnectionScope$$inlined$CoroutineExceptionHandler$1@3595913
    at kotlinx.coroutines.JobKt__JobKt.getJob(Job.kt:645)
    at kotlinx.coroutines.JobKt.getJob(Unknown Source:1)
    at com.juul.kable.BluetoothDeviceAndroidPeripheral.<init>(BluetoothDeviceAndroidPeripheral.kt:74)
    at com.juul.kable.PeripheralKt.peripheral(Peripheral.kt:30)
    at com.juul.kable.PeripheralKt.peripheral(Peripheral.kt:47)
    at com.juul.kable.PeripheralKt.peripheral$default(Peripheral.kt:42)
```

For reference, the `createConnectionScope` function creates the scope which I use for all BLE operations and looks like this:
```
@OptIn(DelicateCoroutinesApi::class)
private fun createConnectionScope(): CoroutineScope = GlobalScope + CoroutineExceptionHandler { _, throwable ->
    Timber.e(throwable)
}
```

Using `CoroutineScope(SupervisorJob() + Dispatchers.Default)` instead of `GlobalScope` works. The issue is not present in 0.27.0.

**Comment by twyatt** [comment]
Thanks for the regression report.
Swamped with some projects at work, but I'll try to look into it soonish.
